spring.application.name=seaty
spring.main.banner-mode=off
spring.mvc.problemdetails.enabled=true
spring.datasource.url=jdbc:sqlite:file:./data/app.db?mode=ro&foreign_keys=true
spring.datasource.hikari.connection-init-sql=PRAGMA query_only=ON
auth.secret=${SEATY_AUTH_SECRET}
